# Generated by Django 5.2 on 2025-05-04 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('setor', models.CharField(choices=[('Tecnologia da Informação', 'Tecnologia da Informação'), ('Recursos Humanos', 'Recursos Humanos'), ('Financeiro', 'Financeiro'), ('Administrativo', 'Administrativo')], max_length=100)),
                ('codigo', models.IntegerField()),
                ('grupos', models.ManyToManyField(blank=True, related_name='dashboards', to='auth.group')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setor'],
            },
        ),
    ]
