# Generated by Django 5.2 on 2025-04-30 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('usuarios', models.ManyToManyField(related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
